name = "remix-cloudflare-workers-vmwpa"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]
routes= ["remix-test-vmwpa.whitepants.store/*"]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

